name: python-linting
on: [push]
jobs:
  linting:
    strategy:
      matrix:
        os: [window-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Linting
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort flake8 mypy pycodestyle
      - name: Lint with isort
        run: |
          isort --check-only --diff .
      - name: Lint with flake8
        run: |
          flake8 --max-line-length=1000 .
      - name: Lint with pycodestyle
        run: |
          pycodestyle --ignore=E501,W504 .